=== Create Docker Images

`mvn package -Pdocker` for each repo will create the Docker image.

By default, the Docker image name is `arungupta/<service>` where `<service>` is `greeting`, `name` or `webapp`. 
Run this command in each directory which contains clones from github (microservices-greeting, microservices-name, microservices-webapp)

  $ mvn package -Pdocker
  
The image can be created in your repo:

  mvn package -Pdocker -Ddocker.repo=<repo>

By default, the `latest` tag is used for the image. A different tag may be specified as:

  mvn package -Pdocker -Ddocker.tag=<tag>

=== Running Docker container from local repository

  $ Docker run -d -p 8081:8081 arungupta/greeting
  $ curl http://localhost:8081/resources/greeting

=== Push Docker Images to Registry

(Important) Attach AmazonEC2ContainerRegistryFullAccess Policy to k8s-workshop-LabIdeRole-xxx Role through AWS IAM console or using aws-cli. 

Create ECR repository to deploy docker into ECS. 
  $ aws ecr create-repository --repository-name greeting
  $ aws ecr create-repository --repository-name name
  $ aws ecr create-repository --repository-name webapp

Tag each docker image to push into ECR.

  $ docker tag <image id> <account id>.dkr.ecr.us-east-1.amazonaws.com/greeting
  $ docker tag <image id> <account id>.dkr.ecr.us-east-1.amazonaws.com/name
  $ docker tag <image id> <account id>.dkr.ecr.us-east-1.amazonaws.com/webapp

Push each docker images to the registry:

  $ docker push <account id>.dkr.ecr.us-east-1.amazonaws.com/greeting
  $ docker push <account id>.dkr.ecr.us-east-1.amazonaws.com/name
  $ docker push <account id>.dkr.ecr.us-east-1.amazonaws.com/webapp

==== Debug

. List containers:

  docker container ls -f name=myapp*

. Get logs for all the containers in the `webapp` service:

  docker service logs myapp_webapp-service
